# Generated by Django 4.2.2 on 2023-07-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='adult_ADHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testId', models.IntegerField(verbose_name='정신질환명 ID')),
            ],
        ),
        migrations.CreateModel(
            name='mental_illness_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mental_illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testId', models.IntegerField(verbose_name='정신질환명 ID')),
                ('name', models.CharField(max_length=300, verbose_name='정신질환명')),
                ('count1', models.FloatField()),
                ('count2', models.FloatField()),
                ('count3', models.FloatField()),
                ('count4', models.FloatField()),
                ('count5', models.FloatField()),
                ('count6', models.FloatField()),
                ('count7', models.FloatField()),
                ('count8', models.FloatField()),
                ('count9', models.FloatField()),
                ('count10', models.FloatField()),
                ('score', models.IntegerField(verbose_name='')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.mental_illness_category')),
            ],
        ),
    ]
