# Generated by Django 4.2.2 on 2023-07-10 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0006_adult_adhd_mental_illness_category_mental_illness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('text', 'Text'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('number', 'Number')], default='text', max_length=10)),
                ('is_number', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('number_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='adult_ADHD',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count1',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count10',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count2',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count3',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count4',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count5',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count6',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count7',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count8',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='count9',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='score',
        ),
        migrations.RemoveField(
            model_name='mental_illness',
            name='testId',
        ),
        migrations.DeleteModel(
            name='mental_illness_category',
        ),
    ]
